### ISSUE TITLE
Automatically add the `mn` catalog when shared plugin is applied

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-build#331]
There was a discussion over here https://github.com/micronaut-projects/micronaut-problem-json/pull/172#issuecomment-1117075127 where we decided that it is cleaner to include micronaut dependencies under an `mn` prefix in the catalog using the following in `settings.gradle`

```groovy
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        "mn" {
            from("io.micronaut:micronaut-bom:${providers.gradleProperty("micronautVersion").get()}")
        }
    }
}
```

Instead of doing this in every project, would it be possible for the settings plugin to set this up for us when it is applied to the build in a module?  Then we can just go back to using

```groovy
plugins {
    id 'io.micronaut.build.shared.settings' version '5.3.x'
}
```

and remove all the micronaut prefixed libraries from the libs.versions.toml files

**Comment by melix** [comment]
This can be done since 5.3.6 using:

```
micronautBuild {
    importMicronautCatalog()
}
```

(the project template has been updated with this).
