### ISSUE TITLE
How does one allow snapshot dependencies during development?

### ISSUE THREAD

**Issue by rlubke** [micronaut-projects/micronaut-build#359]
We want to test with a SNAPSHOT dependency during development of our project, however, the bom validation fails the build stating there are snapshot dependencies present.

Is there a way to do this without changing the micronaut build extension and implementation itself as it seems it doesn't expose anything in this area.

**Comment by alvarosanchez** [comment]
You can apply some exclusions to the BOM validation feature: https://github.com/micronaut-projects/micronaut-build/wiki/Upgrade-guide#bom-validation
