### ISSUE TITLE
Add configuration macro for showing either Properties file or YAML or TOML etc. snippets

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-build#438]
Since we are moving to properties files by default for Micronaut 4 it is critical that all configuration file snippets show both Java properties and YAML config in a tab based snippet preview similar to our Gradle/Maven switcher. 

It would be nice to be implement do something like:

```
[.configuration]
----
foo.bar=test
foo.baz=stuff
----
```

Will need a tree processor https://docs.asciidoctor.org/asciidoctorj/latest/extensions/treeprocessor/

**Comment by melix** [comment]
Do you want something which would automatically convert yaml to toml, or would we have to write both syntaxes and it's only about a dual pane view?

**Comment by graemerocher** [comment]
defining Java properties like:

```
[.configuration]
----
foo.bar=test
foo.baz=stuff
----
```

Should automatically generate the equivalent YAML/TOML/HOCON/Java properties snippets with tabs without the need to duplicate

In Java properties form lists are specified with indexes:


```
[.configuration]
----
foo.bar[0]=test
foo.bar[1]=test
----
```
