### ISSUE TITLE
Surface Checkstyle errors in the Build Scan

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-build#451]
It would be cool to be able to see the Checkstyle failures in the scan itself

Like so:

https://docs.gradle.com/enterprise/tutorials/extending-build-scans/#surface_static_code_analysis_issues_in_build_scans

**Comment by timyates** [comment]
Actually, ignore this, you can [see them in the console log](https://ge.micronaut.io/s/erv4cetphmoz2/console-log?task=:core-processor:checkstyleMain) 🙄

**Comment by alvarosanchez** [comment]
Note you can also see them in Sonar
