### ISSUE TITLE
Gradle Enterprise is now develocity

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-build#618]
See https://gradle.com/develocity

This will imply plugin coordinate and DSL changes. These are visible in some screenshots but I couldn't find proper upgrade docs yet.

**Comment by sdelamo** [comment]
I think @timyates  has changed it in every repo.

**Comment by timyates** [comment]
I changed all the "revved up" badges in our repos.

I was looking at this last week, and as far as I can see, the rename has not yet made it to the plugins, so currently there's nothing else to do

**Comment by sdelamo** [comment]
I am closing this. I think it is done.
