### ISSUE TITLE
Investigate how Micronaut modules are bringing the Micronaut BOM

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-build#68]
Currently, this plugin makes all modules to have [a dependency on `micronaut-bom`](https://github.com/micronaut-projects/micronaut-build/blob/master/src/main/groovy/io/micronaut/build/MicronautBuildCommonPlugin.groovy#L54).

This can be disabled by declaring:

```groovy
micronautBuild {
    enableBom = false
}
```

Perhaps we should set the default value of `enableBom` to `false`. In which case, all the modules will have to reference Micronaut artifacts by the exact version

**Comment by jameskleeh** [comment]
Is it not possible to enable a dependency on the bom but exclude it from publishing? That was the goal I left with

**Comment by alvarosanchez** [comment]
I don't get what you mean. Exclude what from publishing? Are you suggesting changing it from `implementation` to `compileOnly`?

**Comment by jameskleeh** [comment]
@alvarosanchez By excluding it from publishing I'm referring to removing the `dependencyManagement` section in the pom

**Comment by alvarosanchez** [comment]
I think the only thing we can try is changing it from `implementation` to `compileOnly`
